---
title: "2019data"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(purrr)
library(ggthemes)
library(dplyr)
library(ggplot2)
```

```{r}
input2019 <- read_xlsx("C:/me/Bayer-input/data_ai_level/2019_Active level_DTU_priority data_scenario 2018.xlsx")

files <- list.files(path = "C:/me/Database/harmonization/", pattern = "*.xlsx", full.names = TRUE)
file_name <- list.files(path = "C:/me/Database/harmonization/", pattern = "*.xlsx")

readexcel <- function(x, y){
  #browser()
  x <- read_excel(x)
  y <- gsub(".xlsx", "", y)
  assign(y, x, envir = .GlobalEnv)
}

map2(files, file_name, readexcel)


harmonization_country <- read_xlsx("C:/me/Database/harmonization/harmonization_country.xlsx", sheet = 1)
harmonization_crop <- read_xlsx("C:/me/Database/harmonization/harmonization_crop.xlsx", sheet = 1)
harmonization_casrn <- read_xlsx("C:/me/Database/harmonization/harmonization_casrn.xlsx", sheet = 1)
harmonization_bbch <- read_xlsx("C:/me/Database/harmonization/harmonization_bbch.xlsx", sheet = 1)
harmonization_app <- read_xlsx("C:/me/Database/harmonization/harmonization_app.xlsx", sheet = 1)
harmonization_source <- read_xlsx("C:/me/Database/harmonization/harmonization_source.xlsx", sheet = 1)
harmonization_moa <- read_xlsx("C:/me/Database/harmonization/harmonization_moa.xlsx", sheet = 1)
```

```{r}
#left join to the harmonization_country table, change if the parameter names change
#n_distinct(input2019$name_country_bayer)
#sort(unique(input2019$name_country_bayer))
n_distinct(input2019$name_app)
input2019_cntr <- input2019 %>%
  left_join(harmonization_country, by = c("name_country_bayer" = "name_country_bayer"))


# check if all countries can be allocated
# currently no records for CENTRAL AMERICA-CARIBBEAN and change them still to CENTRAL AMERICA-CARIBBEAN
input2019_cntrna <- input2019_cntr %>%
  filter(is.na(name_country))
n_distinct(input2019_cntrna$name_country_bayer)
input2019_cntr <- input2019_cntr %>% 
  mutate(name_country = replace_na(name_country, "CENTRAL AMERICA-CARIBBEAN"))

totalmass2019 <- sum(input2019_cntr$applied_mass_kkg)
totalarea2019 <- sum(input2019_cntr$treated_area_kha)
input2019_cntrmass <- input2019_cntr %>%
  group_by(name_country) %>%
  summarize(mass = sum(applied_mass_kkg), area = sum(treated_area_kha), massratio = round(mass/totalmass2019,2), arearatio = round(area/totalarea2019,2))
```

```{r}
# left join to the harmonization_crop table, change if the parameter names change
# crop2019 <- input2019 %>%
#   group_by(name_crop_bayer, name_cropgroup_bayer, name_cropmaingroup) %>%
#   summarize(mass = sum(applied_mass_kkg), area = sum(treated_area_kha),count = n())
# crop2019_check <- crop2019 %>%
#   full_join(harmonization_crop, by = c("name_crop_bayer" = "name_crop_bayer")) %>%
#   select(name_crop_bayer, name_cropgroup_bayer, name_crop_earthstat) %>%
#   mutate(exist2019 = case_when(is.na(name_cropgroup_bayer) ~ "n",
#                            TRUE ~ "y"),
#          exist2018 = case_when(is.na(name_crop_earthstat) ~ "n",
#                                TRUE ~ "y"))
# write.csv(crop2019_check, "crop2019check.csv")
# n_distinct(input2019$name_crop_bayer)
input2019_crop <- input2019_cntr %>%
  left_join(harmonization_crop, by = c("name_crop_bayer" = "name_crop_bayer"))

# check if all crops can be allocated
# change after confirmation of the crop names
input2019_cropna <- input2019_crop %>%
  filter(is.na(name_crop_earthstat))
n_distinct(input2019_cropna$name_crop_bayer)
sort(unique(input2019_cropna$name_crop_bayer))

n_distinct(input2019_crop$name_crop_earthstat)

input2019_cropcntr <- input2019_crop %>%
  group_by(name_country, name_crop_earthstat, name_cropgroup, name_region) %>%
  summarize(mass = sum(applied_mass_kkg), area = sum(treated_area_kha)) %>%
  ungroup() %>%
  group_by(name_country) %>%
  mutate(massratio = round(mass/sum(mass), 2), arearatio = round(area/sum(area),2)) %>%
  mutate(year = "2019")

#input_cropcntr <- rbind(input2019_cropcntr, input2020_cropcntr)

#check 2019 source
n_distinct(input2019$name_source)
input2019_cropcntrsource <- input2019_crop %>%
  group_by(name_country, name_crop_earthstat, name_source) %>%
  summarize(count2019 = n())


#heatmap for crop country 
input2019_cropcntr %>% 
  ggplot(., aes(x = name_crop_earthstat, y = name_country, fill = mass)) + 
  geom_tile(color="white",size=0.1) + 
  #scale_fill_viridis(discrete = FALSE, option = "D") + 
  scale_fill_gradient2(mid = "light grey", high = "darkred", limits = c(0,40000), oob = scales::squish, na.value = "light grey") +
  coord_equal() + 
  theme_tufte(base_family="Helvetica") +
  theme(axis.ticks=element_blank()) +
  theme(axis.text=element_text(size=8)) +
  theme(axis.text.x = element_text(angle = 90))+
  theme(panel.spacing.x=unit(1, "cm")) +
  theme(panel.spacing.y=unit(0.5, "cm"))  +
  theme(strip.text=element_text(hjust=0)) +
  theme(plot.title=element_text(hjust=0)) +
  theme(panel.border=element_blank()) +
  theme(legend.title=element_text(size=6)) +
  theme(legend.title.align=1) +
  theme(legend.text=element_text(size=6)) +
  theme(legend.position="bottom") +
  theme(legend.key.size=unit(0.2, "cm")) +
  theme(legend.key.width=unit(1, "cm")) +
  labs(x = "crop", y = "country")
```

```{r}
input2019_cropcntr %>%
  filter(name_country != "Spain") %>%
  ggplot(., aes(x = name_crop_earthstat, y = name_country, fill = mass)) +
  geom_raster() + 
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  scale_fill_gradient(trans = "log", low = "lightgrey", high = "darkred", breaks = c(0.2, 20, 3000, 100000)) +
  facet_grid(rows = vars(name_region), 
             cols = vars(name_cropgroup), scales = "free", space="free")
```

```{r}
input2019_cropcntrnospain <- input2019_cropcntr %>%
  filter(name_country!= "Spain") %>%
  mutate(name_crop_earthstat = case_when(name_crop_earthstat == "other" ~ "z_other",
                                         TRUE ~ name_crop_earthstat))
input2020_cropcntrnospain <- input2020_cropcntr %>%
  filter(name_country!= "Spain") %>%
  mutate(name_crop_earthstat = case_when(name_crop_earthstat == "other" ~ "z_other",
                                         TRUE ~ name_crop_earthstat))
p <- input2020_cropcntr %>%
  filter(name_country != "Spain") %>%
  ggplot(., aes(x = name_crop_earthstat, y = name_country, fill = mass)) +
  geom_raster() + 
  geom_point(data = input2019_cropcntrnospain, aes(x = name_crop_earthstat, y = name_country, color = mass), shape = 19, size = 2) +
  scale_color_gradient(low = "gray", high = "blue", trans = "log",  breaks = c(0.2, 20, 3000, 100000)) +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  scale_fill_gradient(trans = "log",  low = "lightgrey", high = "darkred",breaks = c(0.2, 20, 3000, 100000)) +
  facet_grid(rows = vars(name_region), 
             cols = vars(name_cropgroup), scales = "free", space="free")
p
ggsave("p.png",width = 50, height = 50, units = "cm")
```

```{r}
input2019_cropcntrnospain <- input2019_cropcntr %>%
  filter(name_country!= "Spain")
p <- input2020_cropcntr %>%
  filter(name_country != "Spain") %>%
  ggplot(., aes(x = name_crop_earthstat, y = name_country, fill = area)) +
  geom_raster() + 
  geom_point(data = input2019_cropcntrnospain, aes(x = name_crop_earthstat, y = name_country, color = area), shape = 19, size = 2) +
  scale_color_gradient(low = "gray", high = "blue", trans = "log",  breaks = c(0.2, 20, 3000, 10000)) +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  scale_fill_gradient(trans = "log",  low = "lightgrey", high = "darkred",breaks = c(0.2, 20, 3000, 10000)) +
  facet_grid(rows = vars(name_region), 
             cols = vars(name_cropgroup), scales = "free", space="free")
p
ggsave("area.png",width = 50, height = 50, units = "cm")
```

```{r}
p <-ggplot() +
  geom_point(data = input2020_cropcntrnospain, aes(x = name_crop_earthstat, y = name_country, color = mass), shape = 15, size = 4) +
  scale_color_gradient(trans = "log",  low = "lightgrey", high = "darkred",breaks = c(0.2, 20, 3000, 100000), name = "2020") +
  #geom_raster() + 
  geom_point(data = input2019_cropcntrnospain, aes(x = name_crop_earthstat, y = name_country, fill = mass, shape = shp), shape = 21, size = 2) +
  scale_fill_gradient(low = "gray", high = "blue", trans = "log",  breaks = c(0.2, 20, 3000, 100000), name= "2019") +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  facet_grid(rows = vars(name_region), 
             cols = vars(name_cropgroup), scales = "free", space="free")
p
ggsave("cropcountry_mass.png",width = 50, height = 50, units = "cm")
```

```{r}
p <-ggplot() +
  geom_point(data = input2020_cropcntrnospain, aes(x = name_crop_earthstat, y = name_country, color = massratio), shape = 15, size = 4) +
  scale_color_gradient(low = "lightgrey", high = "darkred", name = "2020") +
  #geom_raster() + 
  geom_point(data = input2019_cropcntrnospain, aes(x = name_crop_earthstat, y = name_country, fill = massratio, shape = shp), shape = 21, size = 2) +
  scale_fill_gradient(low = "gray", high = "blue",  name= "2019") +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  facet_grid(rows = vars(name_region), 
             cols = vars(name_cropgroup), scales = "free", space="free")
p
ggsave("cropcountry_massratio.png",width = 50, height = 50, units = "cm")
```

```{r}
# left join to the harmonization_casrn table, change if the parameter names change
input2019_cas <- input2019_crop %>%
  mutate(casrn_chemical_bayer = replace_na(casrn_chemical_bayer, "NONE")) %>%
  left_join(harmonization_casrn, by = c("casrn_chemical_bayer" = "casrn_chemical_bayer", "name_ai_bayer" = "name_ai_bayer"))

# check if all crop stages can be allocated
# check in casrn_check.rmd if new cas number introduced
input2019_casna <- input2019_cas %>%
  filter(is.na(casrn_chemical))
n_distinct(input2019_casna$casrn_chemical_bayer)
casna <- input2019_cas %>%
  filter(casrn_chemical_bayer == "NAME") %>%
  distinct(casrn_chemical_bayer, name_activegroup, name_ai_bayer)

# chemical2019 <- input2019_cas %>%
#   group_by(name_ai_bayer, casrn_chemical_bayer, name_activegroup) %>%
#   summarize(mass = sum(applied_mass_kkg), area = sum(treated_area_kha),count = n())
# chemical2019 %>%
#   group_by(casrn_chemical_bayer) %>%
#   summarize(n = n()) %>%
#   filter(n > 1)

# chemical2019_check <- chemical2019 %>%
#   full_join(harmonization_casrn, by = c("casrn_chemical_bayer" = "casrn_chemical_bayer", "name_ai_bayer" = "name_ai_bayer")) %>%
#   select(name_ai_bayer, name_ai, casrn_chemical, casrn_chemical_bayer, mass, area, count, name_activegroup) %>%
#   mutate(exist2019 = case_when(is.na(mass) ~ "n",
#                            TRUE ~ "y"),
#          exist20182019 = case_when(is.na(casrn_chemical) ~ "n",
#                                TRUE ~ "y"))
# write.csv(chemical2019_check, "chemical2019check.csv")

# 17236 records with no cas rn
sum(input2019_nospain$applied_mass_kkg)
input2019_nospain <- input2019 %>%
  filter(name_country_bayer != "SPAIN")
input2019_casname <- input2019_cas %>%
  filter(name_country != "Spain") %>%
  filter(casrn_chemical == "NAME")
input2019_casname_mass <- input2019_casname %>%
  filter(name_country != "Spain") %>%
  group_by(name_ai_bayer) %>%
  summarize(mass = sum(applied_mass_kkg)) %>%
  mutate(massratio = round(mass/5796367,2))
input2019cntr_mass <- input2019_cas %>%
  group_by(name_country) %>%
  summarize(area = sum(treated_area_kha), mass = sum(applied_mass_kkg))
input2019cntr_casnamemass <- input2019_casname %>%
  group_by(name_country, name_chemclass1) %>%
  summarize(namearea = sum(treated_area_kha), namemass = sum(applied_mass_kkg))
input2019cntr_mass <- input2019cntr_mass %>%
  left_join(input2019cntr_casnamemass, by = c("name_country" = "name_country")) %>%
  mutate(arearatio = round(namearea/area,2), massratio = round(namemass/mass,2))

nrow(input2019_casname)/nrow(input2019_cas)
sum(input2019_casname$applied_mass_kkg)/sum(input2019_cas$applied_mass_kkg)


input2019_countrychemclass <- input2019_cas %>%
  group_by(name_country) %>%
  mutate(countrysum = sum(applied_mass_kkg), countrycount = n()) %>%
  ungroup() %>%
  group_by(name_country, name_chemclass, countrysum, countrycount, name_region) %>%
  summarize(summass = sum(applied_mass_kkg), count = n()) %>%
  mutate(massratio = round(summass/countrysum,2), countratio = round(count/countrycount,2))
input2019_countrychemclassnospain <- input2019_countrychemclass %>%
  filter(name_country != "Spain")

input2019_cropchemclass <- input2019_cas %>%
  filter(name_country != "Spain") %>%
  group_by(name_crop_earthstat) %>%
  mutate(cropsum = sum(applied_mass_kkg), cropcount = n()) %>%
  ungroup() %>%
  group_by(name_crop_earthstat, name_chemclass, name_cropgroup, cropsum, cropcount) %>%
  summarize(summass = sum(applied_mass_kkg), count = n()) %>%
  mutate(massratio = round(summass/cropsum,2), countratio = round(count/cropcount,2))



# remove cas rn with names
input_bayer_2018_cas <- input_bayer_2018_cas %>%
  filter(casrn_chemical != "NAME")
```

```{r}
p <-ggplot() +
  geom_point(data = input2020_countrychemclassnospain, aes(x = name_chemclass, y = name_country, color = massratio), shape = 15, size = 4) +
  scale_color_gradient(low = "lightgrey", high = "darkred", name = "2020") +
  #geom_raster() + 
  geom_point(data = input2019_countrychemclassnospain, aes(x = name_chemclass, y = name_country, fill = massratio, shape = shp), shape = 21, size = 2) +
  scale_fill_gradient(low = "gray", high = "blue", name= "2019") +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  facet_grid(rows = vars(name_region), scales = "free", space="free")
p
ggsave("countrychemclass_massratio.png",width = 50, height = 50, units = "cm")
```


```{r}
p <-ggplot() +
  geom_point(data = input2019_cropchemclass, aes(x = name_chemclass, y = name_crop_earthstat, color = massratio), shape = 15, size = 4) +
  scale_color_gradient(low = "lightgrey", high = "darkred", name = "2020") +
  #geom_raster() + 
  geom_point(data = input2020_cropchemclass, aes(x = name_chemclass, y = name_crop_earthstat, fill = massratio, shape = shp), shape = 21, size = 2) +
  scale_fill_gradient(low = "gray", high = "blue", name= "2019") +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  facet_grid(rows = vars(name_cropgroup), scales = "free", space="free")
p
ggsave("cropchemclass_massratio.png",width = 50, height = 50, units = "cm")
```

```{r}
p <-ggplot() +
  geom_point(data = input2020_countrychemclassnospain, aes(x = name_chemclass, y = name_country, color = summass), shape = 15, size = 4) +
  scale_color_gradient(low = "lightgrey", high = "darkred", trans = "log",  breaks = c(0.2, 20, 3000, 100000),name = "2020") +
  #geom_raster() + 
  geom_point(data = input2019_countrychemclassnospain, aes(x = name_chemclass, y = name_country, fill = summass, shape = shp), shape = 21, size = 2) +
  scale_fill_gradient(low = "gray", high = "blue", trans = "log",  breaks = c(0.2, 20, 3000, 100000),name= "2019") +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  facet_grid(rows = vars(name_region), scales = "free", space="free")
p
ggsave("countrychemclass_mass.png",width = 50, height = 50, units = "cm")
```

```{r}
p <-ggplot() +
  geom_point(data = input2019_cropchemclass, aes(x = name_chemclass, y = name_crop_earthstat, color = summass), shape = 15, size = 4) +
  scale_color_gradient(low = "lightgrey", high = "darkred", trans = "log",  breaks = c(0.2, 20, 3000, 100000),name = "2020") +
  #geom_raster() + 
  geom_point(data = input2020_cropchemclass, aes(x = name_chemclass, y = name_crop_earthstat, fill = summass, shape = shp), shape = 21, size = 2) +
  scale_fill_gradient(low = "gray", high = "blue", trans = "log",  breaks = c(0.2, 20, 3000, 100000),name= "2019") +
  #theme_tufte(base_family="Helvetica") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # lables vertical
        #strip.text.y = element_blank()) +  #remove facet bar on y 
  #scale_fill_gradient(low = "lightgrey", high = "darkred") +
  ggtitle("test table") +
  facet_grid(rows = vars(name_cropgroup), scales = "free", space="free")
p
ggsave("cropchemclass_mass.png",width = 50, height = 50, units = "cm")
```

#no need chemical included in cas already
#mode of action
```{r}
input2019_moa <- input2019_cas %>%
  left_join(harmonization_moa, by = c("name_moa" = "name_moa"))

# check if all mode of action can be allocated
input2019_moana <- input2019_moa %>%
  filter(is.na(name_moagroup))
```


```{r}
# left join to the harmonization_bbch table, change if the parameter names change
#n_distinct(input2019$name_cropstage)
input2019_bbch <- input2019_moa %>%
  left_join(harmonization_bbch, by = c("name_cropstage" = "name_cropstage"))

# check if all crop stage can be allocated

input2019_bbchna <- input2019_bbch %>%
  filter(is.na(code_bbch))


# bbch2019 <- input2019_bbch %>%
#   group_by(name_cropstage) %>%
#   summarize(mass = sum(applied_mass_kkg), area = sum(treated_area_kha),count = n())
# 
# bbch2019_check <- bbch2019 %>%
#   full_join(harmonization_bbch, by = c("name_cropstage" = "name_cropstage")) %>%
#   select(name_cropstage, mass, area, count, bbch_group, min, max) %>%
#   mutate(exist2019 = case_when(is.na(mass) ~ "n",
#                            TRUE ~ "y"),
#          exist20182020 = case_when(is.na(bbch_group) ~ "n",
#                                TRUE ~ "y"))
# write.csv(bbch2019_check, "bbch2019_check.csv")
```

```{r}
# left join to harmonization_app table, change if the parameter names change
input2019_app <- input2019_bbch %>%
  left_join(harmonization_app, by = c("name_app" = "name_app"))

# check if all application methods can be allocated
input2019_appna <- input2019_app %>%
  filter(is.na(name_refapp))

app2019 <- input2019_app %>%
  group_by(name_app) %>%
  summarize(mass = sum(applied_mass_kkg), area = sum(treated_area_kha),count = n())
# 
# app2019_check <- app2019 %>%
#   full_join(harmonization_app, by = c("name_app" = "name_app")) %>%
#   select(name_app, mass, area, count, name_refapp) %>%
#   mutate(exist2019 = case_when(is.na(mass) ~ "n",
#                            TRUE ~ "y"),
#          exist2018 = case_when(is.na(name_refapp) ~ "n",
#                                TRUE ~ "y"))
# write.csv(app2019_check, "app2019_check.csv")
```

# input2019 chemical-country-crop group
```{r}
input2019_ccc <- input2019_app %>%
  filter(name_country != "Spain") %>%
  mutate(totalmass2019 = sum(applied_mass_kkg)) %>%
  group_by(name_country) %>%
  mutate(countrymass2019 = sum(applied_mass_kkg)) %>%
  ungroup() %>%
  group_by(name_ai, name_country, name_crop_earthstat, countrymass2019, totalmass2019) %>%
  summarize(summass2019 = sum(applied_mass_kkg)) %>%
  ungroup() %>%
  mutate(countryratio2019 = round(summass2019/countrymass2019,2), totalratio2019 = round(summass2019/totalmass2019,2))


input_ccc <- input2019_ccc %>%
  full_join(input2020_ccc, by = c("name_ai" = "name_ai", "name_country" = "name_country", "name_crop_earthstat" = "name_crop_earthstat"))

n_distinct(input2020_cas$name_cropstage)
```


```{r}
input_chemclass <- input2019_cas %>%
  group_by(name_chemclass) %>%
  summarize(count2019 = n())
```


```{r}
input_bayer_2018_c <- input_bayer_2018_chem %>%
  filter(!is.na(`treated_area_[1000ha/yr]`)) %>%
  filter(`treated_area_[1000ha/yr]` != 0) %>%
  filter(`applied_mass_[1000kg/yr]` != 0) %>%
  mutate(`dose_[kg/ha]` = round(`applied_mass_[1000kg/yr]`/`treated_area_[1000ha/yr]`,2)) %>%
  select(id_bayer, id_scenariobayer, name_country, name_region, name_crop_bayer, name_crop_earthstat, name_crop_FAO, name_cropgroup.x, name_cropgroup.y, casrn_chemical, name_ai, name_cropstage,code_bbch_bayer, `treated_area_[1000ha/yr]`, name_indication, `applied_mass_[1000kg/yr]`, `dose_[kg/ha]`, Product, Distributor)
```

# crop-country multiple source? 
```{r}
input2019_source <- input2019_crop %>%
  left_join(harmonization_source, by = c("name_source" = "name_source"))
input2019_sourcena <- input2019_source %>%
  filter(is.na(name_sourcegroup))
cropcountry2019_source <- input2019_crop %>%
  group_by(name_country, name_crop_earthstat) %>%
  summarize(count = n_distinct(name_source))

source2019 <- input2019_source %>%
  group_by(name_source) %>%
  summarize(count2019 = n()) %>%
  mutate(perc2019 = round(count2019/sum(count2019),2))

source2019 <- data_frame(unique(input2019$name_source))
write.csv(source2019, "source2019.csv")
```

